name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app-backend ./backend && docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app-backend

    - name: Build and push frontend
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app-frontend ./frontend && docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app-frontend

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd my-flask-app
          git pull origin main
          docker compose down
          docker compose pull
          docker compose up -d
